### PR TITLE
99% Of alarm feature implemented, may have minor bugs

### PR DESCRIPTION
**Pull request by engrish555**
The updated PR : Couple of things coming in a future PR :)

This adds an alarm feature to WOPR (sorry had todo some refactoring in the main file)

If there is a V2 board
* Let it have RTC 
* Let it have some form of perm storage (ram or sdcard)
* Let it have some "extra" side buttons to toggle up/down
* Let the reset be easier to get to
* Let it have a rear 3d print case that could hold a battery

### CODE REVIEW

**Comment by UnexpectedMaker** [comment]
Hey mate, so sorry I never saw this!
So after a review, as cool as this all is, it's changed too much in the base display code for me to merge this in... especially considering I also have newer code I'm working on that has none of your refactoring.
Maybe a better idea is for you to just release your fork of this? I'll link to it on the store pages so folks know about it and can use it instead of mine if they like?
Cheers,
Seon

**Comment by UnexpectedMaker** [comment]
Oh, also, re your rev 2 list... you can already store stuff on the ESP32. It uses a system called SPIFFS - there are examples in Arduino in the ESP32 section. Let's you save and load files like a file system.

**Comment by engrish555** [comment]
All good , you have been busy 

I am planning on changing it for the "new" version with back buttons - Hopefully that will result in less core changes

(Some of the core changes mine help re-used the core features ) 

Ill close this PR

**Comment by UnexpectedMaker** [comment]
Yeah, you did some nice changes and I'v already done some similar ones, though not to the same extent. Putting menu names  into an array etc. I'm also using enums now for state as well, and have SPIFFS implemented for user data, so extending that for your alarm stuff should be super simple.

**Pull request closed without merging**
